apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: argo-test
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
